### ISSUE TITLE
Link to technical report is dead

### ISSUE THREAD

**Issue by Mitsos101** [lac-dcc/wyvern#2]
The link <https://lac.dcc.ufmg.br/pubs/TechReports/LaC_TechReport012022.pdf> in the readme is dead.

**Comment by pronesto** [comment]
Fair enough. UFMG's webserver works only when if feels like it... :( I've added the PDF to this repo. The link should work now.

**Comment by pronesto** [comment]
I will be closing the issue. The extra material in the report appears as an appendix. The rest of the report is just like the paper.
